### ISSUE TITLE
Add various examples of using `@github` shortcut

### ISSUE THREAD

**Issue by chshersh** [kowainik/hakyll-shortcut-links#17]
This helps to improve documentation by explaining how shorcutting works. And I always forget difference between `@github(foo)` and `@github:foo`. So I think that the docs should cover the following examples:

- [x] `@github`
- [x] `@github(foo)`
- [x] `@github:bar`
- [x] `@github(foo):bar`

**Comment by Tarektouati** [comment]
i'll do it can you assign me to it

**Comment by vrom911** [comment]
Sure, thank you, @Tarektouati !

**Comment by Tarektouati** [comment]
@chshersh  is it about updating the readme file with new example or the hackage documentation ?

**Comment by chshersh** [comment]
@Tarektouati Let's have it both places: README and top-level module Haddock for the main module in the package. It's more useful and discoverable to have it in two places :slightly_smiling_face:
