### ISSUE TITLE
Check out default options of pandoc writer/reader

### ISSUE THREAD

**Issue by vrom911** [kowainik/hakyll-shortcut-links#5]
At the moment this:
```
"This is [Hello](@github:kowainik) yes no [aelve/shortcut-links](@github)"
```

transforms to:

```
"This is [Hello](https://github.com/kowainik) yes no\n[aelve/shortcut-links](https://github.com/aelve/shortcut-links)"
```

The reason for `\n` could be Pandoc options/limits. Need to investigate

**Comment by chshersh** [comment]
I see the following settings in the default writer options:

```haskell
                      , writerWrapText         = WrapAuto
                      , writerColumns          = 72
```

Here:

* https://hackage.haskell.org/package/pandoc-2.7.2/docs/src/Text.Pandoc.Options.html#line-190

Maybe this is the answer why we see this wrapping...

**Comment by vrom911** [comment]
Oh, I see. Thanks for the investigation, @chshersh ! :+1: 
I don't see that this could be a problem. This is the default behaviour anyway and also we export all the functions so users could use them with any options they want. I think we can close this.
